### ISSUE TITLE
Disappearing text

### ISSUE THREAD

**Issue by fgmccabe** [ckaznocha/ide-go#19]
I am using the latest version of:
-   [ ] Atom
-   [ ] ide-go
-   [ ] atom-ide-ui
-   [ ] go-langserver

**Operating System**:

Mac OS X 

### Expected Behavior

Text should not disappear when saving file

### Actual Behavior

import statement goes missing

### Steps to Reproduce

try to save the following file:

package display

import (
	term "term"
)

type Display interface {
	Show(depth int) string
}

func (Normal *n) Show(depth int) string {
}

you will see that the import statement is removed from the buffer and the file.

**Comment by JerryLiao26** [comment]
Have you use the package you imported in the statement? If not, that's one of the feature of ```goimports```
@frankmccabe

**Comment by ckaznocha** [comment]
`goimports` can take some getting used to. This plugin should be running it on save on you, you've probably got go-plus configured to run it on save.
