### ISSUE TITLE
Package no longer working

### ISSUE THREAD

**Issue by joshua** [ckaznocha/ide-go#28]
After upgrading to Atom 1.28.0, the ide-go package doesn't appear to be working. Outline, hyperclick go-to-def, and hover info is no longer works.

Outline panel says I need to install a supporting IDE package.

![screen shot 2018-06-25 at 2 30 15 pm](https://user-images.githubusercontent.com/1718/41869051-c36d7562-7885-11e8-9595-c272a1a9a69c.png)

Everything was working as expected prior to upgrading. 

I am using the latest version of:
-   [x] Atom
-   [x] ide-go
-   [x] atom-ide-ui
-   [x] go-langserver

**Operating System**: macOS 10.13.1

### Expected Behavior

ide-go features work

### Actual Behavior

ide-go features dont work.

**Comment by joshua** [comment]
I forgot I enabled to new tree sitter feature! 🤦‍♂️

With tree sitter disabled, this package works as expected.

**Comment by ckaznocha** [comment]
I updated the atom-languageclient which looks to have fixed some issues with tree-sitter. Please let me know if you're still having issues.

**Comment by joshua** [comment]
@ckaznocha Thanks for the update. I updated all package, including ide-go, and I'm still experiencing the same issue as before if I enable the tree sitter parser.

**Comment by ckaznocha** [comment]
Found the problem, the tree-sitter scope name changed from `source.go` to `go`. Please update to the latest version to use it with tree-sitter!

**Comment by joshua** [comment]
@ckaznocha works like a charm! Thanks!
