### ISSUE TITLE
Datatip gets stuck on inside inline function

### ISSUE THREAD

**Issue by ermik** [ckaznocha/ide-go#29]
I am using the latest version of:
-   [x] Atom
-   [x] ide-go
-   [x] atom-ide-ui
-   [x] go-langserver

**Operating System**: macOS

### Expected Behavior
As I type the atom-ide-ui `datatip` would dynamically change.

### Actual Behavior
`datatip` overlay element stays the same when working on inline function argument, such as testing package function argument

### Steps to Reproduce
```go
package main

import (
	"testing"
)

func TestDatatipAppearance(t *testing.T) {
	t.Run("function_appearance", func(t *testing.T) {
                // datatip will keep referring to t.Run function as you type here
        })
}
```

**Comment by ckaznocha** [comment]
Hey @ermik I just tried to replicate but I'm not experiencing the same issue as you. Perhaps an update to go-langserver fixed the issue or maybe I'm not replicating correctly? Would you mind confirming this is still an issue?
