### ISSUE TITLE
Doesn't work with nonstandard GOPATH

### ISSUE THREAD

**Issue by treyzania** [ckaznocha/ide-go#30]
I am using the latest version of:
-   [x] Atom Beta (1.29.0-beta2)
-   [x] ide-go (0.7.0)
-   [x] atom-ide-ui (0.13.0)
-   [x] go-langserver (v2-dev)

```
$ apm-beta --version
apm  1.19.0C
npm  3.10.10
node 6.9.5 x64
atom 1.29.0-beta2
python 2.7.15
git 2.18.0
```

**Operating System**: Debian buster/sid (DE: xfce4)

### Expected Behavior

Working.

### Actual Behavior

Nothing.  The "working" cursor appears when I hover over an identifier and hold ctrl but it just stays like that indefinitely, but otherwise it's almost like the plugin isn't even installed.  I wanted to use this plugin since `go-plus` is very laggy when typing.  There aren't any messages in the console, either.

### Steps to Reproduce

* Install the plugin

* Open a Go source file

* Try to do something that would trigger some behavior, like typing `fmt.`.

**Comment by treyzania** [comment]
Figured it out:

You're not paying attention to `$GOPATH`.  I have it set in my `.profile` to `$HOME/.go` instead of `$HOME/go` to avoid cluttering my homedir.

**Comment by ckaznocha** [comment]
Hi @treyzania, I'm sorry you had issues getting set up. It does respect your `$GOPATH`, in fact it borrows the same function from go-plus to do so: https://github.com/ckaznocha/ide-go/blob/master/lib/ide-go.ts#L120

It sounds like perhaps your `~/.profile` isn't getting sourced properly when atom sets up your env, but that's just a guess. Glad you got it working!
