### ISSUE TITLE
IDE-Go without Go-Plus not working

### ISSUE THREAD

**Issue by appelgriebsch** [ckaznocha/ide-go#39]
I am using the latest version of:
-   [ x ] Atom
-   [ x ] ide-go
-   [ ] atom-ide-ui
-   [ x ] go-langserver

**Operating System**:

### Expected Behavior

After installing the ide-go package and the go-langserver I would expect the go-langserver to deliver langserver information to Atom(-IDE) for any Go source file. An installation of go-plus is no longer necessary (see changelog for v0.10.0).

### Actual Behavior

Due to a check in the language-client.ts file (https://github.com/ckaznocha/ide-go/blob/master/lib/language-client.ts#L150-L152) the language server will not be started as long as the services GoConfig and GoGet from the go-plus package have not been registered.

**Comment by appelgriebsch** [comment]
Ok, my fault. It checks for a valid package setting holding the path to the go-langserver, and additionally requires the Atom-IDE-busy-signal package as prerequisite.

**Comment by ckaznocha** [comment]
Hey @appelgriebsch, sorry you had issues but I'm glad you got it working! Is there something that could be put in the README to make it more clear for future users?
