### ISSUE TITLE
Do I need to install go-plus?

### ISSUE THREAD

**Issue by kifirkin** [ckaznocha/ide-go#4]
Also if I do, I have some warnings like:
```
Choose a linter UI

You have both linter and atom-ide-diagnostics enabled, which will both display lint results for Linter-based packages.

To avoid duplicate results, please disable one of the packages.
```

**Comment by ckaznocha** [comment]
Hi @alexmironof, Yes you need go-plus installed. I'm leveraging it to set up the go env and download the go-langserver binary if its missing.

The other message you're getting is a conflict between linter and atom-ide-ui. You can safely disable/uninstall the linter package. The go-plus package may give you a nag to re-install in though. There is an open issue for that: https://github.com/joefitzgerald/go-plus/issues/682

**Comment by kifirkin** [comment]
@ckaznocha Thanks for the response! :+1:

**Comment by ckaznocha** [comment]
Actually, its not intended to be a feature but if you set an absolute path to `go-langserver` in the `ide-go` settings everything should work correctly without go-plus installed. `ide-go` will still ask you to install `go-plus` but that would be an easy fix.

**Comment by kifirkin** [comment]
Ill test both possibilities on different machines and post the results here

**Comment by lazdmx** [comment]
@ckaznocha I think that `go-plus` must be listed as direct dependency in README
