### ISSUE TITLE
Do you have any plan to support bingo, gopls?

### ISSUE THREAD

**Issue by saibing** [ckaznocha/ide-go#42]
I am using the latest version of:
-   [ ] Atom
-   [ ] ide-go
-   [ ] atom-ide-ui
-   [ ] go-langserver

**Operating System**:

### Expected Behavior
There are some new go language server tool, can you support them?

[gopls](https://github.com/golang/tools/blob/master/cmd/gopls/main.go)

[bingo](https://github.com/saibing/bingo)

**Comment by appelgriebsch** [comment]
Got it working without touching the source code...

![Sample DataTip](https://user-images.githubusercontent.com/6803419/54620734-e627d300-4a66-11e9-943f-8f660e404638.PNG)

here my settings:

![IDE-Go Settings](https://user-images.githubusercontent.com/6803419/54620759-ee800e00-4a66-11e9-8134-26bec4f82d6f.PNG)

Note that you have to deselect the optional flags, so the ide-go will not call the binary with parameters. 

As a side-note you will get the langserver is outdated notification any time, but you can easily close this.

**Comment by saibing** [comment]
@appelgriebsch 

Thank you very much for your workaround

**Comment by slnt** [comment]
So `bingo` works, although it provides some very odd things that really shouldn't be errors.

(@saibing it compiles just fine under `go build` but `bingo` reports type mismatches when it shouldn't -- stuff like `cannot use start (variable of type time.Time) as time.Time value in argument to myFuncName`)

`gopls` doesn't seem to work from what I can tell -- I turned off all of the optional flags and such but it doesn't do anything?
